### ISSUE TITLE
Pronóstico

### ISSUE THREAD

**Issue by CarlosBoulder** [Komando4ediae/komando4Project#16]
El Algoritmo necesita saber  qué es un pronóstico óptimo para poder ir a escalar el día deseado. Nos referimos a esta HU #9 y al Milestone 0 Modelado de datos

**Comment by JJ** [comment]
Todos los issues
* Tienen que estar en un milestone, para entender perfectamente hacia qué PMV se trabaja
* Tienen que estar asignado a una persona *en GitHub*, no de vivo a voz.
* Tienen que *referirse a una historia de usuario*, porque si no no sabemos este código a qué ayuda.
