### ISSUE TITLE
Problema: como relacionar los datos

### ISSUE THREAD

**Issue by DaniWalkington** [Komando4ediae/komando4Project#41]
Tenemos los modelos de datos necesarios para resolver los problemas de la Historia de Usuario 1 #9 , necesitamos ahora una entidad que lea los parámetros (condiciones óptimas) y los datos (localización, pronóstico) y que, dependiendo de los que sean, devuelva un valor booleano que indique la viabilidad para escalar.

**Comment by JJ** [comment]
Procesar los datos es el milestone 1. Aquí tenéis simplemente que resolver el problema de como contener esos datos y qué relación hay entre los diferentes objetos valor.
