### ISSUE TITLE
Actualizar forecast.js

### ISSUE THREAD

**Issue by DaniWalkington** [Komando4ediae/komando4Project#44]
Hay un error ortográfico en forecast.js que debe ser solucionado. Además hay que añadirle docstrings que expliquen el código, como hemos hecho con otros archivos. Este issue forma parte de la #9 .

**Comment by CarlosBoulder** [comment]
Hay un error ortográfico en el issue, pone "otrográfico"

**Comment by DaniWalkington** [comment]
Cierto, ahora lo cambio 👍
